-- Exo 1.1

CREATE TABLE T_office
(
	office_id INTEGER,
	office_address VARCHAR(30),
	CONSTRAINT PK_office PRIMARY KEY (office_id)
)

CREATE TABLE T_course
(
	crs_code CHAR(8) NOT NULL PRIMARY KEY,
	crs_name VARCHAR(30),
	CONSTRAINT UK_crs UNIQUE(crs_name)
)

CREATE TABLE T_professor -- incorrect : NOT NULL PAS NECESS SUR PK, FK et UNIQUE
(
    prf_id INTEGER NOT NULL PRIMARY KEY,
    prf_name VARCHAR(30),
    prf_course CHAR(8),
    crs_code CHAR,
    office_id INTEGER,
    CONSTRAINT FK_course FOREIGN KEY(crs_code)
    REFERENCES T_course(crs_code)
    ON DELETE SET NULL,
    CONSTRAINT FK_office FOREIGN KEY(office_id)
    REFERENCES T_office(office_id),
    CONSTRAINT UK_prf_name UNIQUE(prf_name)
)

-- Exo 1.2
CREATE TABLE T_maintenance_mtn
(
	jour CHAR(8) PRIMARY KEY,
	machine VARCHAR(30) NOT NULL,
	numero INTEGER NOT NULL UNIQUE,
	vitesse INTEGER CHECK (vitesse between 0 and 20),
	temperature INTEGER,
	heure TIME NOT NULL,
	evenement VARCHAR(60) NOT NULL
)

-- Exo 1.3
CREATE TABLE T_produit_pdt
(
	identifiant INTEGER PRIMARY KEY,
	ref_magasin VARCHAR(20) NOT NULL UNIQUE,
	ref_fabricant INTEGER NOT NULL UNIQUE,
	ean13 CHAR(13) UNIQUE,
	prix_vente DECIMAL(6,2),
	taux_tva INTEGER
	
  	CONSTRAINT FK_fbq FOREIGN KEY(ref_fabricant)
  	REFERENCES T_fabriquant_fbq(ref_fabricant),
	CONSTRAINT FK_magasin FOREIGN KEY(ref_magasin)
  	REFERENCES T_rayon_ryn(ref_magasin),
	CONSTRAINT FK_tva FOREIGN KEY(taux_tva)
  	REFERENCES T_taux_tva(taux_tva)
)

-- Exo 1.4
CREATE TABLE T_VOITURE_VTR (
    VTR_ID              INTEGER         NOT NULL PRIMARY KEY,
    VTR_IMMATRICUL      CHAR(10)        NOT NULL UNIQUE,
    VTR_CARBURANT       CHAR(2)         NOT NULL DEFAULT 'ES' CHECK(VTR_CARBURANT IN ('ES','GO','PL')),
    VTR_PUISSANCE_FISC  INTEGER         NOT NULL CHECK(VTR_PUISSANCE_FISC BETWEEN 1 AND 20),
    VTR_NB_PLACES       INTEGER         NOT NULL CHECK(VTR_NB_PLACES BETWEEN 1 AND 7),
    VTR_MODELE          VARCHAR(20)     CHECK(BTRIM(VTR_MODELE) <> ''),
    VTR_CONSTRUCTEUR    VARCHAR(16)     CHECK(BTRIM(VTR_CONSTRUCTEUR) <> ''),
    VTR_NUMERO_SERIE    VARCHAR(25)     NOT NULL CHECK(BTRIM(VTR_NUMERO_SERIE) <> ''),
    CONSTRAINT CK_IMMATRICULATION CHECK(
        ((CAST(SUBSTRING(VTR_IMMATRICUL, 9, 1) AS INTEGER) BETWEEN 0 AND 9)
        AND (SUBSTRING(VTR_IMMATRICUL, 10, 1) BETWEEN '0' AND '9')
        AND (SUBSTRING(VTR_IMMATRICUL, 9, 2) < '96'))
        OR ((CAST(SUBSTRING(VTR_IMMATRICUL, 9, 1) AS INTEGER) = 2)
        AND (SUBSTRING(VTR_IMMATRICUL, 10, 1) IN ('A', 'B')))),
    CONSTRAINT CK_PUISS_PLACE   CHECK(VTR_NB_PLACES - 1 < VTR_PUISSANCE_FISC),
    CONSTRAINT UK_MDL_CTR_NSR   UNIQUE (VTR_MODELE, VTR_CONSTRUCTEUR, VTR_NUMERO_SERIE)
);

INSERT INTO T_VOITURE_VTR VALUES (14, '478 XDA 78', 'ES', 9, 5, '305', 'PEUGEOT', '00014578');
INSERT INTO T_VOITURE_VTR VALUES (31, '1447 MD 44', 'ES', '7', 5, NULL, 'CITROEN', '0001578'); -- Erreur car string pour INTEGER
INSERT INTO T_VOITURE_VTR VALUES (7, '5475 MRT 91', 'GO', 5, 4, '204', 'PEUGEOT', '0001474578'); -- Erreur car immatriculation trop longue
INSERT INTO T_VOITURE_VTR VALUES (11, '1744 BC 76', 'GO', 7, 5, NULL, NULL, '00025678'); -- PAS ERREUR car '' != NULL
INSERT INTO T_VOITURE_VTR VALUES (15, '4412 LR 75', 'GO', 7, 4, '305', 'PEUGEOT', '00014578'); -- Erreur car modele-constr-numserie déjà présent
INSERT INTO T_VOITURE_VTR VALUES (17, '971 VTR 96', NULL, 7, 5, '306', 'PEUGEOT', '00017548'); -- Erreur car CARB vide et 96
INSERT INTO T_VOITURE_VTR VALUES (19, '991 SDT 75', 'ES', 8, 5, 'MEGANE', 'RENAULT', '00014578');
INSERT INTO T_VOITURE_VTR VALUES (20, '991 SDT 75', 'ES', 5, 4, 'MEGANE', 'RENAULT', '00014578'); -- Erreur car déjà présent
INSERT INTO T_VOITURE_VTR VALUES (14, '4875 ZT 94', NULL, 7, 5, NULL, 'RENAULT', '005784'); -- Erreur car CARB vide et 14 PK déjà présente
INSERT INTO T_VOITURE_VTR VALUES (7, '5474 MRT 91', 'GPL', 5, 4, 'PT CRUISER', 'CHRYSLER', '0000050214'); -- Erreur car immatriculation trop longue