from abc import ABC, abstractmethod

class IAnimal(ABC):
    @abstractmethod
    def eat(self): ...
    @abstractmethod
    def observe_environment(self): ...
    @abstractmethod
    def take_a_nap(self): ...
    @abstractmethod
    def death_probability(self): ...
    @abstractmethod
    def grows_hungry(self): ...
    @abstractmethod
    def grows_sad(self): ...